# Generated by Django 6.0.3 on 2026-04-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_posts_image_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='topic',
            field=models.CharField(default='general', max_length=50),
            preserve_default=False,
        ),
    ]
